const els = {
  bgVideo: document.getElementById("bg-video"),
  bgImage: document.getElementById("bg-image"),
  emptyState: document.getElementById("empty-state"),
  clockWrap: document.getElementById("clock-wrap"),
  clockTime: document.getElementById("clock-time"),
  clockDate: document.getElementById("clock-date"),
  settingsToggle: document.getElementById("settings-toggle"),
  settingsPanel: document.getElementById("settings-panel"),
  fileInput: document.getElementById("file-input"),
  uploadStatus: document.getElementById("upload-status"),
  clockToggle: document.getElementById("clock-toggle"),
  removeMediaBtn: document.getElementById("remove-media"),
  hoverRevealToggle: document.getElementById("hover-reveal-toggle"),
  searchWrap : document.getElementById("search-wrap"),
  searchInput : document.getElementById("search-input"),
  DisplayTabs : document.getElementById("display-tabs"),
  engineButton : document.getElementById("search-engine"),
  engineList : document.getElementById("search-engine-list"),
  autocomplete : document.getElementById("search-autocomplete"),
  overlay: document.getElementById("notesOverlay"),
  close: document.getElementById("closeNotes"),
  listView: document.getElementById("notesListView"),
  list: document.getElementById("notesList"),
  count: document.getElementById("notesCount"),
  add: document.getElementById("addNote"),
  view: document.getElementById("noteView"),
  backToNotes: document.getElementById("backToNotes"),
  edit: document.getElementById("editNote"),
  delete: document.getElementById("deleteNote"),
  viewTitle: document.getElementById("viewNoteTitle"),
  viewDescription: document.getElementById("viewNoteDescription"),
  form: document.getElementById("noteForm"),
  formTitle: document.getElementById("noteFormTitle"),
  backFromForm: document.getElementById("backFromNoteForm"),
  title: document.getElementById("noteTitle"),
  description: document.getElementById("noteDescription"),
  message: document.getElementById("noteFormMessage"),
  cancel: document.getElementById("cancelNote"),
  save: document.getElementById("saveNote"),
  search: document.getElementById("notesSearch"),
};

export {els }